name: Deploy to Cloudflare Workers

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'pnpm'

    - name: Install pnpm
      run: corepack enable && corepack prepare pnpm@latest --activate

    - name: Install dependencies
      run: pnpm install

    - name: Build Nuxt project
      run: pnpm build

    - name: Deploy to Cloudflare Workers
      env:
        CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      run: pnpm deploy
